### ISSUE TITLE
Router.use() Type Error

### ISSUE THREAD

**Issue by DanielEgan** [regatta-app/api#13]
I am getting this error when trying to use run the api.. any ideas?

C:\projects\regatta-app\api\node_modules\express\lib\router\index.js:458
      throw new TypeError('Router.use() requires middleware function but got a ' + gettype(fn));
      ^

**TypeError: Router.use() requires middleware function but got a Object**
    at Function.use (C:\projects\regatta-app\api\node_modules\express\lib\router\index.js:458:13)
    at EventEmitter.<anonymous> (C:\projects\regatta-app\api\node_modules\express\lib\application.js:219:21)
    at Array.forEach (native)
    at EventEmitter.use (C:\projects\regatta-app\api\node_modules\express\lib\application.js:216:7)
    at Object.<anonymous> (C:\projects\regatta-app\api\index.js:13:5)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

**Comment by DanielEgan** [comment]
If I change 
`export default router;`

to

`module.exports = router;`

in each of the router files, it goes away.  I'm not sure the correct ts code to produce that in the js.

**Comment by DanielEgan** [comment]
Although changing from `export default router;` to `module.exports = router;`  fixed the problem, the root cause was leftover .js and .js.map files in the root folder when we moved session-router and ui-router into a routers folder.  In VS code we had both .js and .js.map files hidden so they were not seen.  Stepping back and cleaning this up solved the issue.  
NOTE: I think that turning off tsc when moving files into folders would help to keep this clean
